"use client";

import { useEffect, useState } from "react";
import AppLayout from "../components/AppLayout";
import { supabase } from "../lib/supabaseClient";

function formatDate(value) {
  if (!value) return "Not set";

  return new Intl.DateTimeFormat("sv-SE", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

function formatStatus(status) {
  if (!status) return "Draft";

  const labels = {
    draft: "Draft",
    pending_approval: "Pending approval",
    approved: "Approved",
    scheduled: "Scheduled",
    published: "Published",
    failed: "Failed",
  };

  return labels[status] || status;
}

function getStatusClass(status) {
  if (status === "pending_approval") return "status-pill warning";
  if (status === "approved") return "status-pill success";
  if (status === "published") return "status-pill success";
  if (status === "failed") return "status-pill danger";

  return "status-pill";
}

export default function Home() {
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");

  useEffect(() => {
    loadPosts();
  }, []);

  async function loadPosts() {
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      window.location.href = "/login";
      return;
    }

    const { data, error } = await supabase
      .from("posts")
      .select(
        "id, platform, tone, language, post_type, idea, content, status, created_at, source, source_label, automation_rule_id, approval_required, approved_at, published_at, scheduled_for"
      )
      .eq("user_id", user.id)
      .order("created_at", { ascending: false });

    if (error) {
      setMessage(error.message);
    }

    if (!error && data) {
      setPosts(data);
    }

    setLoading(false);
  }

  async function deletePost(postId) {
    const confirmDelete = window.confirm("Delete this post?");
    if (!confirmDelete) return;

    setMessage("");

    const { error } = await supabase.from("posts").delete().eq("id", postId);

    if (error) {
      setMessage(error.message);
      return;
    }

    setPosts((currentPosts) =>
      currentPosts.filter((post) => post.id !== postId)
    );

    setMessage("Post deleted.");
  }

  const pendingApprovalCount = posts.filter(
    (post) => post.status === "pending_approval"
  ).length;

  const scheduledCount = posts.filter(
    (post) => post.status === "scheduled"
  ).length;

  const automationCount = posts.filter(
    (post) => post.source === "automation"
  ).length;

  return (
    <AppLayout active="dashboard">
      <header className="topbar">
        <div>
          <p className="eyebrow">Welcome back</p>
          <h2>Your social media workspace</h2>
        </div>
        <a className="primary-button" href="/create">
          Create new post
        </a>
      </header>

      <section className="grid">
        <div className="stat-card">
          <span>Posts created</span>
          <strong>{posts.length}</strong>
        </div>

        <div className="stat-card">
          <span>Pending approval</span>
          <strong>{pendingApprovalCount}</strong>
        </div>

        <div className="stat-card">
          <span>Generated by automation</span>
          <strong>{automationCount}</strong>
        </div>

        <div className="stat-card">
          <span>Scheduled posts</span>
          <strong>{scheduledCount}</strong>
        </div>
      </section>

      <section className="result-card">
        <div className="result-header">
          <div>
            <p className="eyebrow">Saved posts</p>
            <h3>Your posts</h3>
          </div>
          <a className="secondary-button" href="/create">
            New draft
          </a>
        </div>

        {message && <p className="login-message">{message}</p>}

        {loading ? (
          <div className="empty-card">
            <h3>Loading posts...</h3>
            <p>Please wait while Spreelo loads your saved posts.</p>
          </div>
        ) : posts.length === 0 ? (
          <div className="empty-card">
            <h3>No posts yet</h3>
            <p>
              Your generated and saved posts will appear here once you start
              creating content.
            </p>
          </div>
        ) : (
          <div className="posts-list">
            {posts.map((post) => {
              const isAutomationPost = post.source === "automation";
              const sourceLabel =
                post.source_label ||
                (isAutomationPost ? "Generated by automation" : "Manual draft");

              return (
                <article className="post-item" key={post.id}>
                  <div className="post-item-header">
                    <div>
                      <h4>
                        {post.platform || "Platform not set"} ·{" "}
                        {post.post_type || "Post"}
                      </h4>

                      <p>
                        {post.tone || "Tone not set"} ·{" "}
                        {post.language || "Language not set"} · {sourceLabel}
                      </p>

                      <div className="post-meta-row">
                        <span className={getStatusClass(post.status)}>
                          {formatStatus(post.status)}
                        </span>

                        {isAutomationPost && (
                          <span className="status-pill">
                            Generated by automation
                          </span>
                        )}

{post.status === "pending_approval" && post.approval_required && (
  <span className="status-pill">Approval required</span>
)}
                      </div>
                    </div>

                    <div className="post-actions">
                      <span>{formatDate(post.created_at)}</span>

                      <a
                        className="secondary-button small-button"
                        href={`/posts/${post.id}`}
                      >
                        Open / Edit
                      </a>

                      <button
                        type="button"
                        className="danger-button"
                        onClick={() => deletePost(post.id)}
                      >
                        Delete
                      </button>
                    </div>
                  </div>

                  <div className="idea-box">
                    <p>
                      <strong>Created:</strong> {formatDate(post.created_at)}
                    </p>

                    {post.scheduled_for && (
                      <p>
                        <strong>Scheduled/generated for:</strong>{" "}
                        {formatDate(post.scheduled_for)}
                      </p>
                    )}

                    {post.approved_at && (
                      <p>
                        <strong>Approved:</strong>{" "}
                        {formatDate(post.approved_at)}
                      </p>
                    )}

                    {post.published_at && (
                      <p>
                        <strong>Published:</strong>{" "}
                        {formatDate(post.published_at)}
                      </p>
                    )}
                  </div>

                  <div className="post-preview compact">
                    {(post.content || "")
                      .split("\n")
                      .slice(0, 6)
                      .map((line, index) => (
                        <p key={index}>{line || "\u00A0"}</p>
                      ))}
                  </div>
                </article>
              );
            })}
          </div>
        )}
      </section>
    </AppLayout>
  );
}
