'use client';
import {useEffect,useState} from 'react';
import {BrainCircuit,RefreshCw,Save,ShieldCheck,TriangleAlert,FlaskConical,Mail,CheckCircle2,X,ExternalLink} from 'lucide-react';
import AppLayout from '../../../components/AppLayout';
import {supabase} from '../../../lib/supabaseClient';

async function headers(){const {data:{session}}=await supabase.auth.getSession();return {'Content-Type':'application/json',...(session?.access_token?{Authorization:`Bearer ${session.access_token}`}:{})};}
const buttonStyle={padding:'10px 15px',borderRadius:10,border:'1px solid #cbd5e1',cursor:'pointer',fontWeight:600};
const purple={...buttonStyle,background:'#5147cb',borderColor:'#5147cb',color:'#fff'};
const TESTABLE_PURPOSES=new Set(['post_text','product_research','editorial_headline','carousel_creative','standard_image','transparent_typography','kling_video']);
const panel={background:'#fff',border:'1px solid #e2e8f0',borderRadius:14,padding:18};
function translatedStatus(test){if(!test)return '';if(test.status==='approved')return 'Modellen är aktiverad';if(test.status==='rejected')return 'Behållit tidigare modell';if(test.email_state==='sent')return test.status==='failed'?'Testet misslyckades – rapport skickad':'Klart – kontrollera mejlen';if(test.email_state==='failed')return 'Mejlleveransen misslyckades';return 'Testet körs – mejl skickas automatiskt när resultatet är klart';}

export default function AiControlPage(){
 const [news,setNews]=useState([]),[watchRun,setWatchRun]=useState(null),[newsError,setNewsError]=useState('');
 const [catalog,setCatalog]=useState([]),[pricing,setPricing]=useState([]),[klingNotice,setKlingNotice]=useState(''),[retrying,setRetrying]=useState(''),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[warning,setWarning]=useState('');
 const [intelligence,setIntelligence]=useState(null),[intelligenceError,setIntelligenceError]=useState('');
 const [autoJobs,setAutoJobs]=useState(null),[autoJobsLoading,setAutoJobsLoading]=useState(true),[autoJobsBusy,setAutoJobsBusy]=useState(false),[autoJobsError,setAutoJobsError]=useState('');
 const [dialog,setDialog]=useState(null),[brands,setBrands]=useState([]),[history,setHistory]=useState([]),[chosenBrand,setChosenBrand]=useState(''),[busy,setBusy]=useState(false),[dialogError,setDialogError]=useState(''),[testDetail,setTestDetail]=useState(null);
 async function load(){setLoading(true);setErr('');try{const r=await fetch('/api/admin/ai-control',{headers:await headers(),cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not load AI Control Center');setItems((j.purposes||[]).map(x=>({...x,savedModel:x.model})));setWarning(j.catalogWarning||'');setCatalog(j.catalog||[]);setPricing(j.pricing||[]);setKlingNotice(j.klingDiscovery||'');}catch(e){setErr(e.message)}finally{setLoading(false)}}
 async function loadIntelligence(){try{const r=await fetch('/api/admin/ai-model-intelligence',{headers:await headers(),cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Modellbevakningen är inte tillgänglig');setIntelligence(j);setIntelligenceError('');}catch(e){setIntelligenceError(e.message)}}
 async function loadAutoJobs(){
  setAutoJobsLoading(true);
  try {const r=await fetch('/api/admin/ai-automation-settings',{headers:await headers(),cache:'no-store'});
    const j=await r.json();if(!r.ok)throw new Error(j.error||'Kunde inte läsa AI-brytaren');
    setAutoJobs(j.enabled===true);setAutoJobsError('');
  }catch(e){setAutoJobs(null);setAutoJobsError(e.message)}finally{setAutoJobsLoading(false)}
 }
 async function toggleAutoJobs(){
  if(autoJobs===null||autoJobsBusy)return;
  const next=!autoJobs;
  if(next && !window.confirm('Aktivera alla fyra nya AI-bakgrundsjobb? Modellkontroller kan göra API-anrop som kostar pengar. Inga aktiva modeller byts automatiskt.'))return;
  setAutoJobsBusy(true);setAutoJobsError('');
  try {const r=await fetch('/api/admin/ai-automation-settings',{method:'PATCH',headers:await headers(),body:JSON.stringify({enabled:next})});
    const j=await r.json();if(!r.ok)throw new Error(j.error||'Kunde inte spara brytaren');
    setAutoJobs(j.enabled===true);setMsg(j.enabled?'Automatiska AI-jobb har aktiverats.':'Automatiska AI-jobb är avstängda.');
  }catch(e){setAutoJobsError(e.message);await loadAutoJobs()}finally{setAutoJobsBusy(false)}
 }
 async function loadTestSetup(){try{const r=await fetch('/api/admin/ai-model-tests',{headers:await headers(),cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Kunde inte hämta testföretag');setBrands(j.brands||[]);setHistory(j.tests||[]);setChosenBrand(old=>old||(j.brands||[])[0]?.id||'');}catch(e){setDialogError(e.message)}}
 async function refreshTest(id){if(!id)return;try{const r=await fetch(`/api/admin/ai-model-tests?id=${encodeURIComponent(id)}`,{headers:await headers(),cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Kunde inte hämta testresultat');setTestDetail(j);}catch(e){setDialogError(e.message)}}
 useEffect(()=>{load();loadIntelligence();loadAutoJobs();loadTestSetup();(async()=>{try{const r=await fetch('/api/admin/ai-market-news',{headers:await headers(),cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'News unavailable');setNews(j.items||[]);setWatchRun(j.lastRun||null);}catch(e){setNewsError(e.message)}})();const testId=new URLSearchParams(window.location.search).get('testId');if(testId){setDialog({phase:'waiting',testId});refreshTest(testId)}},[]);
 useEffect(()=>{if(!dialog?.testId||['approved','rejected'].includes(testDetail?.test?.status))return;const timer=setInterval(()=>refreshTest(dialog.testId),9000);return ()=>clearInterval(timer)},[dialog?.testId,testDetail?.test?.status]);
 function change(key,model){setItems(v=>v.map(x=>x.key===key?{...x,model}:x));}
 async function saveDirect(item){setSaving(item.key);setMsg('');setErr('');try{const r=await fetch('/api/admin/ai-control',{method:'PATCH',headers:await headers(),body:JSON.stringify({purpose:item.key,model:item.model})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Kunde inte spara modell');setMsg(`${item.label}: ${item.model} används från nästa nya körning.`);setDialog(null);await load();}catch(e){setDialogError(e.message)}finally{setSaving('')}}
 function openChoice(item){if(item.model===item.savedModel)return;setDialogError('');setTestDetail(null);setDialog({phase:'choice',item});loadTestSetup()}
 async function startTest(){if(!chosenBrand||!dialog?.item)return;setBusy(true);setDialogError('');try{const r=await fetch('/api/admin/ai-model-tests',{method:'POST',headers:await headers(),body:JSON.stringify({purpose:dialog.item.key,model:dialog.item.model,brandProfileId:chosenBrand})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Testet kunde inte startas');setDialog(d=>({...d,phase:'waiting',testId:j.id}));setTestDetail(null);await refreshTest(j.id)}catch(e){setDialogError(e.message)}finally{setBusy(false)}}
 async function reviewTest(action){if(!dialog?.testId)return;setBusy(true);setDialogError('');try{const r=await fetch('/api/admin/ai-model-tests',{method:'PATCH',headers:await headers(),body:JSON.stringify({id:dialog.testId,action})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Kunde inte registrera beslutet');setMsg(action==='approve'?`Modellen ${j.model} har aktiverats.`:'Tidigare modell behålls.');setDialog(null);setTestDetail(null);await load();await loadTestSetup()}catch(e){setDialogError(e.message)}finally{setBusy(false)}}
 async function retryCatalog(model){
  if(!window.confirm(`Testa om ${model} med OpenAI? API-kostnad kan tillkomma.`))return;
  setRetrying(model);setErr('');setMsg('');
  try {const r=await fetch('/api/admin/ai-model-review',{method:'POST',headers:await headers(),body:JSON.stringify({model})});const j=await r.json();
    if(!r.ok)throw new Error(j.error||'Testet misslyckades');
    setMsg(j.approved?`${model}: teknisk verifiering godkänd och tillgänglig i rätt dropdown.`:`${model}: fortfarande väntande. ${j.error||''}`);
    await load();
  } catch(e){setErr(e.message)}finally{setRetrying('')}
 }
 function openHistory(h){setDialogError('');setTestDetail(null);setDialog({phase:'waiting',testId:h.id});refreshTest(h.id)}
 const selected = dialog?.item;
 const selectedIsTestOnly=Boolean(selected?.testOnlyModels?.includes(selected?.model));
 const statusTest = testDetail?.test;
 const canReview = statusTest?.status==='ready'&&statusTest?.email_state==='sent';
 return <AppLayout title="AI Control Center">
  <main style={{maxWidth:1180,margin:'0 auto',padding:'28px 24px 60px'}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start',marginBottom:22}}><div><div style={{display:'flex',gap:10,alignItems:'center'}}><BrainCircuit size={28}/><h1 style={{margin:0}}>AI Control Center</h1></div><p style={{maxWidth:760,color:'#64748b'}}>Välj AI-modell per funktion. Testa nya modeller med en verklig adminbutik innan du aktiverar dem. Befintliga modeller används tills du godkänner ett byte.</p></div><button onClick={()=>{load();loadIntelligence();loadAutoJobs()}} style={buttonStyle}><RefreshCw size={16}/> Synka</button></div>
   {warning&&<div style={{padding:14,border:'1px solid #f59e0b',borderRadius:12,marginBottom:14}}><TriangleAlert size={17}/> {warning}</div>}
   {err&&<div style={{padding:14,border:'1px solid #ef4444',borderRadius:12,marginBottom:14}}>{err}</div>}{msg&&<div style={{padding:14,border:'1px solid #22c55e',borderRadius:12,marginBottom:14}}>{msg}</div>}
   <section style={{...panel,marginBottom:18,borderColor:autoJobs===true?'#bbf7d0':'#cbd5e1'}}>
    <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',flexWrap:'wrap',gap:12}}>
     <div><h2 style={{fontSize:17,margin:'0 0 6px'}}>Automatiska AI-bevakningar</h2>
      <div style={{fontSize:13,color:'#475569'}}>Nyheter, modellupptäckt, pris- och tillgänglighetskontroll samt leverans av AI-modelltesternas resultatmejl.</div>
      <div style={{fontSize:13,marginTop:8,fontWeight:700,color:autoJobs===true?'#166534':'#92400e'}}>
       {autoJobsLoading?'Kontrollerar status…':autoJobs===null?'Status kan inte läsas':autoJobs?'På – schemalagda jobb tillåtna':'Av – schemalagda jobb stoppas säkert'}
      </div>
     </div>
     <button style={autoJobs===true?buttonStyle:purple} disabled={autoJobsBusy||autoJobsLoading||autoJobs===null} onClick={toggleAutoJobs}>
      {autoJobsBusy?'Sparar…':autoJobs===true?'Stäng av automatiska AI-jobb':'Aktivera automatiska AI-jobb'}
     </button>
    </div>
    {autoJobsError&&<p style={{color:'#b91c1c',fontSize:13,margin:'10px 0 0'}}>{autoJobsError}</p>}
    {autoJobs!==true&&<p style={{color:'#64748b',fontSize:12,margin:'10px 0 0'}}>När brytaren är avstängd skickas inte modelltesternas automatiska resultatmejl. Aktivera den före en admin-testkörning. Vanliga kundkörningar och manuella modellbyten påverkas inte.</p>}
   </section>
   <div style={{display:'grid',gap:12}}>{loading?<p>Laddar…</p>:items.map(item=><section key={item.key} style={{...panel,display:'grid',gridTemplateColumns:'minmax(200px,1.4fr) minmax(190px,1fr) auto',gap:14,alignItems:'center'}}><div><strong>{item.label}</strong><div style={{fontSize:13,color:'#64748b',marginTop:5}}>{item.provider==='kling'?'Kling':'OpenAI'} · {item.capability}</div>{item.capability==='image_alpha'&&<div style={{fontSize:12,color:'#166534',marginTop:6}}><ShieldCheck size={14}/> Kräver verifierad alpha-transparens</div>}<div style={{fontSize:12,color:'#64748b',marginTop:5}}>Aktiv: <strong>{item.savedModel}</strong>{item.active_missing_from_listing&&<span style={{display:'block',color:'#b45309'}}>Modellen finns inte i senaste API-listningen – kontrollera tillgängligheten före byte.</span>}</div></div><select aria-label={`Modell för ${item.label}`} value={item.model} onChange={e=>change(item.key,e.target.value)} style={{padding:'10px 12px',border:'1px solid #cbd5e1',borderRadius:9,minWidth:0,width:'100%'}}>{item.options.map(m=><option key={m} value={m}>{m}{m===item.default_model?' · v322':''}{item.testOnlyModels?.includes(m)?' · endast test':''}</option>)}</select><button disabled={saving===item.key||item.model===item.savedModel} onClick={()=>openChoice(item)} style={purple}><Save size={16}/> {saving===item.key?'Sparar…':'Spara / byt'}</button></section>)}</div>
   <section style={{...panel,marginTop:24}}>
    <h2 style={{margin:'0 0 8px',fontSize:19}}>AI Model Intelligence – priser och modellbevakning</h2>
    <p style={{fontSize:13,color:'#64748b'}}>Officiella listpriser, kontroller av aktiva modellernas API-tillgänglighet och förslag på tekniskt verifierade ersättare. <strong>Ingen modell byts automatiskt.</strong></p>
    {intelligenceError&&<p style={{fontSize:13,color:'#b45309'}}>Bevakningen är inte tillgänglig: {intelligenceError}. Kör den samlade v329-SQL-filen före användning.</p>}
    {intelligence&&<>
      <p style={{fontSize:12,color:'#64748b'}}>Senaste dagliga kontroll: {intelligence.lastRun?.checked_at?new Date(intelligence.lastRun.checked_at).toLocaleString('sv-SE'):'Ingen kontroll registrerad'} · Priser verifierade: {intelligence.lastRun?.results?.pricing?.verified??'–'} · Priser ej tillgängliga: {intelligence.lastRun?.results?.pricing?.unavailable??'–'} · Mejllarm: {intelligence.lastRun?.mail_status||'–'}</p>
      {(intelligence.recommendations||[]).length>0&&<div style={{marginBottom:16}}><h3 style={{fontSize:15,margin:'14px 0 8px'}}>Modeller att kontrollera</h3>{intelligence.recommendations.map(rec=><div key={rec.purpose} style={{padding:12,border:'1px solid #facc15',borderRadius:10,marginBottom:8}}><strong>{rec.label}: {rec.model}</strong><div style={{fontSize:12,color:'#92400e',marginTop:5}}>Saknas i {rec.missingDays} dagliga API-listningar. Detta är inte bekräftad avveckling.</div>{rec.candidate?<div style={{fontSize:13,marginTop:6}}>Verifierad ersättningskandidat: <strong>{rec.candidate.model}</strong>. {rec.candidate.comparison?`Exempelkostnad ${rec.candidate.comparison.oldCost.toFixed(2)} → ${rec.candidate.comparison.newCost.toFixed(2)} USD (1M input + 1M output).`: 'Jämförbart pris saknas.'}<button style={{...buttonStyle,marginLeft:9,fontSize:12,padding:'5px 9px',background:'#fff'}} onClick={()=>{const item=items.find(x=>x.key===rec.purpose);if(item&&item.options.includes(rec.candidate.model)){openChoice({...item,model:rec.candidate.model})}else setErr('Ersättaren finns inte bland valbara modeller. Synkronisera och kontrollera verifieringen.') }}>Välj och testa modellen</button></div>:<p style={{fontSize:12,color:'#64748b'}}>Ingen verifierad ersättare finns ännu. Befintligt modellval förblir oförändrat.</p>}</div>)}</div>}
      {(intelligence.comparisons||[]).length>0&&<><h3 style={{fontSize:15,margin:'14px 0 8px'}}>Prisjämförelser – textmodeller</h3><p style={{fontSize:12,color:'#64748b'}}>USD standardpris för ett exempel med 1 miljon input-tokens och 1 miljon output-tokens. Inte kostnaden för ett färdigt inlägg. Andra tokenmängder, bild- och videopriser ingår inte.</p><div style={{display:'grid',gap:6}}>{intelligence.comparisons.slice(0,15).map(c=><div key={`${c.purpose}:${c.candidateModel}`} style={{padding:'9px 10px',border:'1px solid #e2e8f0',borderRadius:8,fontSize:12,display:'flex',flexWrap:'wrap',gap:12,justifyContent:'space-between'}}><span><strong>{c.label}</strong> · {c.currentModel} → {c.candidateModel}</span><span>{c.oldCost.toFixed(2)} → {c.newCost.toFixed(2)} USD {c.percentDifference===null?'':`(${c.percentDifference>0?'+':''}${c.percentDifference}%)`}</span></div>)}</div></>}
      {(intelligence.recommendations||[]).length===0&&(intelligence.comparisons||[]).length===0&&<p style={{fontSize:13,color:'#64748b'}}>Inga verifierade prisjämförelser eller upprepade API-varningar att visa ännu.</p>}
      <p style={{fontSize:12,color:'#64748b',marginTop:12}}>Kling-priser hämtas inte automatiskt eftersom de inte kan jämföras säkert med OpenAI-tokenpriser. Även om en modell saknas i en API-lista fortsätter Spreelo använda ditt befintliga modellval tills du själv gör ett byte.</p>
    </>}
   </section>
   <section style={{...panel,marginTop:24}}><h2 style={{margin:'0 0 8px',fontSize:19}}>Modelltester</h2><p style={{color:'#64748b',fontSize:13}}>Testkörningar använder endast företag på aktiva adminkonton. Inläggen skickas till contact@spreelo.com utan publicering eller kundkrediter.</p>{history.length?history.map(h=><button key={h.id} onClick={()=>openHistory(h)} style={{...buttonStyle,display:'flex',justifyContent:'space-between',alignItems:'center',width:'100%',background:'#fff',marginBottom:7,textAlign:'left'}}><span><strong>{h.model}</strong> · {h.purpose}<small style={{display:'block',fontSize:11,color:'#64748b'}}>{new Date(h.created_at).toLocaleString('sv-SE')}</small></span><span style={{fontSize:12,color:'#64748b'}}>{h.status==='ready'?'Väntar på ditt beslut':h.status==='approved'?'Godkänd':h.status==='rejected'?'Avböjd':h.status==='failed'?'Misslyckades':'Pågår'}</span></button>):<p style={{fontSize:13,color:'#94a3b8'}}>Inga modelltester ännu.</p>}</section>
   <section style={{...panel,marginTop:24}}><h2 style={{margin:'0 0 8px',fontSize:19}}>Modellregister och automatisk granskning</h2><p style={{fontSize:13,color:'#64748b'}}>OpenAI-modeller upptäcks dagligen. Nya text- och bildmodeller provas med begränsade riktiga API-anrop. Godkända funktioner blir automatiskt valbara i dropdownlistorna; befintliga modeller byts aldrig automatiskt. Provet kontrollerar teknisk funktion, inte kreativ kvalitet.</p><p style={{fontSize:12,color:'#64748b'}}>{klingNotice}</p>{catalog.length===0?<p style={{fontSize:13,color:'#94a3b8'}}>Inga upptäckta modeller än. Den dagliga kontrollen behöver köras efter SQL-installationen.</p>:<div style={{maxHeight:390,overflowY:'auto',display:'grid',gap:6}}>{catalog.slice(0,70).map(c=><div key={`${c.provider}:${c.model}`} style={{padding:'9px 10px',border:'1px solid #e2e8f0',borderRadius:8,display:'flex',justifyContent:'space-between',alignItems:'start',gap:12,flexWrap:'wrap'}}><div style={{minWidth:180}}><strong style={{fontSize:13}}>{c.model}</strong><div style={{fontSize:11,color:'#64748b'}}>{c.provider} · {c.verified_capabilities?.length?c.verified_capabilities.join(', '):'Ingen kapacitet verifierad'}</div>{c.verification_notes&&<div style={{fontSize:11,color:'#64748b',maxWidth:620,marginTop:3}}>{c.verification_notes.slice(0,240)}</div>}</div><div style={{display:'flex',gap:8,alignItems:'center'}}><span style={{fontSize:12,color:c.status==='approved'?'#166534':'#a16207'}}>{c.status==='approved'?'Godkänd':c.status==='rejected'?'Avvisad':'Väntar på godkänt test'}</span>{c.status==='pending_review'&&c.provider==='openai'&&<button disabled={retrying===c.model} onClick={()=>retryCatalog(c.model)} style={{...buttonStyle,fontSize:11,padding:'5px 8px',background:'#fff'}}>{retrying===c.model?'Testar…':'Testa igen'}</button>}</div></div>)}</div>}<p style={{fontSize:12,color:'#64748b',marginTop:12}}>Priser visas endast när ett belopp och dess källa har verifierats. Saknas ett pris betyder det inte att modellen är gratis.</p>{pricing.length>0&&<div style={{display:'grid',gap:5}}>{pricing.slice(0,30).map(c=><div key={`${c.provider}:${c.model}:${c.unit}`} style={{display:'flex',justifyContent:'space-between',gap:12,fontSize:12,borderTop:'1px solid #e2e8f0',paddingTop:6}}><span>{c.model} · {c.unit}</span><a target="_blank" rel="noopener noreferrer" href={c.source_url}>{Number(c.amount_usd).toFixed(6)} USD · verifierad källa</a></div>)}</div>}</section>
   <section style={{...panel,marginTop:24}}><h2 style={{margin:'0 0 8px'}}>AI-nyheter & rekommendationer</h2><p style={{color:'#64748b',fontSize:13}}>Daglig bevakning av officiella AI-leverantörsflöden. Inga modeller byts av bevakningen.</p><p style={{fontSize:12,color:'#64748b'}}>Senaste kontroll: {watchRun?.checked_at?new Date(watchRun.checked_at).toLocaleString('sv-SE'):'Ingen kontroll registrerad ännu'} · Källor OK: {watchRun?.sources_ok??'–'} · Misslyckade: {watchRun?.sources_failed??'–'}</p>{newsError&&<p style={{color:'#b45309'}}>Nyhetsflödet är inte tillgängligt. {newsError}</p>}{!newsError&&news.length===0&&<p style={{color:'#64748b'}}>Inga relevanta nyheter registrerade ännu.</p>}<div style={{display:'grid',gap:10}}>{news.map(n=><article key={n.id} style={{padding:'12px 0',borderTop:'1px solid #e2e8f0'}}><strong style={{color:n.severity==='critical'?'#b91c1c':n.severity==='important'?'#b45309':'#334155'}}>{n.severity==='critical'?'Viktigt':n.severity==='important'?'Bevaka':'Info'}</strong> <span style={{fontSize:12,color:'#64748b'}}>{n.provider} · {new Date(n.published_at||n.discovered_at).toLocaleDateString('sv-SE')}</span><div><a href={n.url} target="_blank" rel="noopener noreferrer" style={{fontWeight:600}}>{n.title}</a></div><p style={{fontSize:13,color:'#64748b',margin:'5px 0 0'}}>{n.summary?.slice(0,240)}</p></article>)}</div></section>
  </main>
  {dialog&&<div role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setDialog(null)}} style={{position:'fixed',inset:0,zIndex:99999,background:'rgba(15,23,42,.58)',backdropFilter:'blur(5px)',display:'flex',alignItems:'center',justifyContent:'center',padding:18}}><div role="dialog" aria-modal="true" aria-label="AI-modelltest" style={{background:'#fff',width:'min(560px,100%)',borderRadius:20,padding:24,maxHeight:'88vh',overflowY:'auto',boxShadow:'0 24px 65px rgba(0,0,0,.22)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><h2 style={{margin:'0 0 10px',fontSize:21,display:'flex',alignItems:'center',gap:10}}><FlaskConical size={22}/> Testa AI-modell</h2><button aria-label="Stäng" style={{...buttonStyle,padding:7,background:'#fff'}} onClick={()=>setDialog(null)}><X size={19}/></button></div>
    {dialogError&&<p style={{color:'#b91c1c',padding:12,background:'#fef2f2',borderRadius:10}}>{dialogError}</p>}
    {dialog.phase==='choice'&&<><p style={{color:'#64748b',lineHeight:1.6}}>Du vill ändra <strong>{selected?.label}</strong> från <strong>{selected?.savedModel}</strong> till <strong>{selected?.model}</strong>.</p><h3>Vill du skapa ett testinlägg innan bytet?</h3><p style={{color:'#64748b',fontSize:13}}>Den befintliga modellen fortsätter användas tills du godkänner resultatet.</p>{selectedIsTestOnly&&<p style={{fontSize:13,color:'#a16207'}}>Den här Kling-modellen måste först klara ett riktigt videottest och godkännas. Direktbyte är spärrat.</p>}{autoJobs!==true&&<p style={{fontSize:13,color:'#b45309'}}>Aktivera automatiska AI-jobb högst upp på sidan för att få testresultatet via mejl.</p>}{!TESTABLE_PURPOSES.has(selected?.key)&&<p style={{fontSize:13,color:'#b45309'}}>Den här funktionen har ännu ingen motsvarande admin-testkörning. Du kan byta utan test.</p>}<div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button style={purple} disabled={!TESTABLE_PURPOSES.has(selected?.key)||autoJobs!==true} onClick={()=>setDialog(d=>({...d,phase:'brand'}))}><FlaskConical size={16}/> Ja, testa först</button><button style={buttonStyle} disabled={saving===selected?.key||selectedIsTestOnly} onClick={()=>saveDirect(selected)}>Nej, byt direkt</button></div></>}
    {dialog.phase==='brand'&&<><p style={{color:'#64748b',fontSize:14}}>Välj ett företag från ett aktivt adminkonto. Testet använder den vanliga motorn och företagets riktiga webbutik.</p><label style={{fontSize:13,fontWeight:700,display:'block',marginBottom:8}}>Testföretag</label><select value={chosenBrand} onChange={e=>setChosenBrand(e.target.value)} style={{width:'100%',padding:12,borderRadius:10,border:'1px solid #cbd5e1',marginBottom:8}}>{brands.length?brands.map(b=><option key={b.id} value={b.id}>{b.name} – {b.website}</option>):<option value="">Inga godkända adminbutiker hittades</option>}</select><p style={{color:'#64748b',fontSize:12}}>Resultatet mejlas automatiskt till contact@spreelo.com. Inget publiceras. AI-leverantörens normala kostnad tillkommer.</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button style={purple} disabled={busy||!chosenBrand||autoJobs!==true} onClick={startTest}>{busy?'Startar…':'Starta testkörning'}</button><button style={buttonStyle} onClick={()=>setDialog(d=>({...d,phase:'choice'}))}>Tillbaka</button></div></>}
    {dialog.phase==='waiting'&&<><p style={{lineHeight:1.6}}><Mail size={18} style={{verticalAlign:'middle',marginRight:8}}/>{translatedStatus(statusTest)}</p>{statusTest&&<p style={{color:'#64748b',fontSize:13}}>Testmodell: <strong>{statusTest.model}</strong> · Funktion: {statusTest.purpose}<br/>Mejl: <strong>contact@spreelo.com</strong>{statusTest.email_error&&statusTest.email_state==='failed'?<><br/>Fel: {statusTest.email_error}</>:null}</p>}{testDetail?.post?.image_url&&<img alt="Genererat testinlägg" src={testDetail.post.image_url} style={{width:'100%',maxHeight:280,objectFit:'contain',borderRadius:10}}/>}{testDetail?.post?.video_url&&<p><a href={testDetail.post.video_url} target="_blank" rel="noopener noreferrer">Visa videon <ExternalLink size={14}/></a></p>}{statusTest?.email_state==='failed'&&<button style={buttonStyle} disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/admin/ai-model-tests',{method:'PATCH',headers:await headers(),body:JSON.stringify({id:dialog.testId,action:'retry_email'})});const j=await r.json();if(!r.ok)throw new Error(j.error);await refreshTest(dialog.testId)}catch(e){setDialogError(e.message)}finally{setBusy(false)}}}>Försök skicka mejlet igen</button>}{statusTest?.status==='failed'&&<p style={{fontSize:13,color:'#b91c1c'}}>Genereringen lyckades inte. Den aktiva modellen har inte ändrats.</p>}{canReview&&<><p style={{fontSize:13,color:'#64748b'}}>Granska mejlet innan du bestämmer dig.</p><div style={{display:'flex',flexWrap:'wrap',gap:10}}><button style={purple} disabled={busy} onClick={()=>reviewTest('approve')}><CheckCircle2 size={17}/> Godkänn test och byt</button><button style={buttonStyle} disabled={busy} onClick={()=>reviewTest('reject')}>Behåll nuvarande modell</button></div></>}{statusTest?.status==='approved'&&<p style={{color:'#166534'}}>Modellbytet är godkänt.</p>}{statusTest?.status==='rejected'&&<p>Den gamla modellen används fortfarande.</p>}{!canReview&&statusTest?.status!=='failed'&&statusTest?.status!=='approved'&&statusTest?.status!=='rejected'&&<p style={{fontSize:12,color:'#64748b'}}>Du kan stänga rutan. Testet fortsätter och resultatet skickas när det är klart.</p>}{statusTest?.batch_id&&<p><a href={`/admin/post-approvals?view=queue&testBatch=${encodeURIComponent(statusTest.batch_id)}`} target="_blank" rel="noopener noreferrer" style={{fontSize:13}}>Visa körningen i admin <ExternalLink size={14}/></a></p>}</>}
   </div></div>}
 </AppLayout>;
}
