"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import AppLayout from "../../../components/AppLayout";
import { supabase } from "../../../lib/supabaseClient";

function formatDate(value) {
  if (!value) return "Not set";

  return new Intl.DateTimeFormat("sv-SE", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

function formatStatus(status) {
  if (!status) return "Draft";

  const labels = {
    draft: "Draft",
    pending_approval: "Pending approval",
    approved: "Approved",
    scheduled: "Scheduled",
    published: "Published",
    failed: "Failed",
  };

  return labels[status] || status;
}

function getStatusClass(status) {
  if (status === "pending_approval") return "status-pill warning";
  if (status === "approved") return "status-pill success";
  if (status === "published") return "status-pill success";
  if (status === "failed") return "status-pill danger";

  return "status-pill";
}

export default function EditPostPage() {
  const params = useParams();
  const postId = params.id;

  const [post, setPost] = useState(null);
  const [content, setContent] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [approving, setApproving] = useState(false);

  useEffect(() => {
    async function loadPost() {
      const {
        data: { user },
      } = await supabase.auth.getUser();

      if (!user) {
        window.location.href = "/login";
        return;
      }

      const { data, error } = await supabase
        .from("posts")
        .select(
          "id, platform, tone, language, post_type, idea, content, status, created_at, updated_at, source, source_label, automation_rule_id, approval_required, approved_at, published_at, scheduled_for"
        )
        .eq("id", postId)
        .eq("user_id", user.id)
        .single();

      if (error) {
        setMessage(error.message);
      }

      if (data) {
        setPost(data);
        setContent(data.content || "");
      }

      setLoading(false);
    }

    if (postId) {
      loadPost();
    }
  }, [postId]);

  async function savePost() {
    setSaving(true);
    setMessage("");

    const { data, error } = await supabase
      .from("posts")
      .update({
        content,
        updated_at: new Date().toISOString(),
      })
      .eq("id", postId)
      .select(
        "id, platform, tone, language, post_type, idea, content, status, created_at, updated_at, source, source_label, automation_rule_id, approval_required, approved_at, published_at, scheduled_for"
      )
      .single();

    if (error) {
      setMessage(error.message);
    } else {
      setPost(data);
      setContent(data.content || "");
      setMessage("Post updated.");
    }

    setSaving(false);
  }

  async function approvePost() {
    const confirmApprove = window.confirm(
      "Approve this post? It will be marked as approved, but it will not be published to social media yet."
    );

    if (!confirmApprove) return;

    setApproving(true);
    setMessage("");

    const approvedAt = new Date().toISOString();

    const { data, error } = await supabase
      .from("posts")
      .update({
        content,
        status: "approved",
        approved_at: approvedAt,
        updated_at: approvedAt,
      })
      .eq("id", postId)
      .select(
        "id, platform, tone, language, post_type, idea, content, status, created_at, updated_at, source, source_label, automation_rule_id, approval_required, approved_at, published_at, scheduled_for"
      )
      .single();

    if (error) {
      setMessage(error.message);
    } else {
      setPost(data);
      setContent(data.content || "");
      setMessage("Post approved.");
    }

    setApproving(false);
  }

  if (loading) {
    return (
      <AppLayout active="dashboard">
        <section className="empty-card">
          <h3>Loading post...</h3>
          <p>Please wait while Spreelo loads your post.</p>
        </section>
      </AppLayout>
    );
  }

  if (!post) {
    return (
      <AppLayout active="dashboard">
        <section className="empty-card">
          <h3>Post not found</h3>
          <p>This post could not be found or you do not have access to it.</p>
          <br />
          <a className="primary-button" href="/">
            Back to dashboard
          </a>
        </section>
      </AppLayout>
    );
  }

  const isPendingApproval = post.status === "pending_approval";
  const isAutomationPost = post.source === "automation";
  const sourceLabel =
    post.source_label ||
    (isAutomationPost ? "Generated by automation" : "Manual draft");

  return (
    <AppLayout active="dashboard">
      <header className="topbar">
        <div>
          <p className="eyebrow">
            {isPendingApproval ? "Review post" : "Edit post"}
          </p>
          <h2>
            {isPendingApproval
              ? "Review and approve this post"
              : "Edit your saved post"}
          </h2>
        </div>

        <div className="button-row">
          <a className="secondary-button" href="/">
            Back
          </a>

          <button
            type="button"
            className="secondary-button"
            onClick={() => navigator.clipboard.writeText(content)}
          >
            Copy text
          </button>

          <button
            type="button"
            className="primary-button"
            onClick={savePost}
            disabled={saving || approving}
          >
            {saving ? "Saving..." : "Save changes"}
          </button>

          {isPendingApproval && (
            <button
              type="button"
              className="primary-button"
              onClick={approvePost}
              disabled={saving || approving}
            >
              {approving ? "Approving..." : "Approve"}
            </button>
          )}
        </div>
      </header>

      <section className="result-card">
        <div className="result-header">
          <div>
            <p className="eyebrow">
              {post.platform || "Platform not set"} ·{" "}
              {post.post_type || "Post"}
            </p>
            <h3>
              {post.tone || "Tone not set"} ·{" "}
              {post.language || "Language not set"}
            </h3>
          </div>

          <div className="post-meta-row">
            <span className={getStatusClass(post.status)}>
              {formatStatus(post.status)}
            </span>

            {isAutomationPost && (
              <span className="status-pill">Generated by automation</span>
            )}
          </div>
        </div>

        <div className="idea-box">
          <p>
            <strong>Source:</strong> {sourceLabel}
          </p>

          <p>
            <strong>Created:</strong> {formatDate(post.created_at)}
          </p>

          {post.scheduled_for && (
            <p>
              <strong>Scheduled/generated for:</strong>{" "}
              {formatDate(post.scheduled_for)}
            </p>
          )}

          {post.approved_at && (
            <p>
              <strong>Approved:</strong> {formatDate(post.approved_at)}
            </p>
          )}

          {post.published_at && (
            <p>
              <strong>Published:</strong> {formatDate(post.published_at)}
            </p>
          )}

          {isPendingApproval && (
            <p>
              <strong>Note:</strong> Approving currently only marks the post as
              approved in Spreelo. Social media publishing will be connected
              later.
            </p>
          )}
        </div>

        <div className="edit-post-grid">
          <div>
            <label className="field-label">Original idea</label>
            <div className="idea-box">
              {post.idea || "No original idea saved."}
            </div>
          </div>

          <div>
            <label className="field-label">Post content</label>
            <textarea
              className="large-textarea"
              value={content}
              onChange={(event) => setContent(event.target.value)}
            />
          </div>
        </div>

        {message && <p className="login-message">{message}</p>}
      </section>
    </AppLayout>
  );
}
